### ISSUE TITLE
One more tool to compare

### ISSUE THREAD

**Issue by zeldigas** [md2conf/md2conf#126]
Hi. I really understand the value of creating your personal tool (it is fun!), just wanted to provide some heads up regarding existing alternatives in addition to documented ones in https://github.com/md2conf/md2conf/blob/master/docs/comparison_with_other_tools.md.

You can take a look at https://github.com/zeldigas/text2confl.

I think, that it has a lot in common with your project - frustration about confluence-publisher asciidoc only and rigid goals of project in general and so on.

Of course it is up to you, feel free to ignore this if you don't see a value.

**Comment by qwazer** [comment]
Zdorovo, Dmitry! :)

Thanks for pointing me on your tool [zeldigas/text2confl](https://github.com/zeldigas/text2confl).

I added `zeldigas/text2confl` to comparison table.
It's very interesting to see how 2 different tools with similar objectives developed independently in the same time =)

It's very likely that if I waited for couple of years in 2021 that decision to start my project was negative I would prefer to contribute to the text2confl. From the other point, the developing of own tool is really fun. The idea to create own tool become to me in 2018. I started from creating test infrastructure in this commit https://github.com/md2conf/atlassian-sdk-confluence/commit/1fc012687a12af52ed77558fe7a5a6fe804c782f.

Nice to meet you. Watching you project now =)

Regards,
Anton.

**Comment by zeldigas** [comment]
Даже не посмотрел на профиль когда писал тикет :). Спасибо что добавили!

А я начинал с попыток улучшений confluence publisher, но там мейнтейнер себе на уме и ничего не смержили. Поэтому решился на свою тулу, с параллельной загрузкой и маркдауном).

Успехов!

**Comment by zeldigas** [comment]
Plantuml с точки зрения кода внешняя зависимостью В докер она попадает просто потому что большинству пользователей нужно что-то готовое а не база по которой они соберут себе что-то :). Но да, тут видение может расходиться.

**Comment by qwazer** [comment]
FYI, added more parameters in comparison. 
https://github.com/md2conf/md2conf/blob/master/docs/comparison_with_other_tools.md
